### ISSUE TITLE
Sorting by compute from largest to smallest does not work

### ISSUE THREAD

**Issue by hendrycks** [lightonai/akronomicon#1] opened 2021-06-11 18:17 UTC

**Comment by slippylolo** [comment] 2021-06-11 18:37
Hey @hendrycks, 

I reproduce this on my browser, thanks for finding it. 

I think it's because one of the entry has an unknown value ("?"). I will look into finding a workaround.

**Comment by slippylolo** [comment] 2021-06-14 10:09
Hey, this should be fixed now (there was actually another issue with the main leaderboard using number of parameters as identifying keys for rows, which broke a lot of things!). 

Thanks for reporting the issue @hendrycks.

**Closed by slippylolo** 2021-06-14 10:09 UTC
Labels: 🏗️ WIP, 🐛 bug
